#!/bin/sh

if [ $# -ne 2 ]
then
    echo "usage: $0 <start|stop> <config>" >&2
    exit 1
fi

action=$1
config=$2

gadget_name=mass-storage

case "$config" in
0)
    nbd_device=/dev/nbd0
    ;;
*)
    echo "invalid config $config" >&2
    exit 1
    ;;
esac

set -ex

case "$action" in
start)
    usb-ctrl insert "$gadget_name" "$nbd_device"
    ;;
stop)
    usb-ctrl eject "$gadget_name"
    ;;
*)
    echo "invalid action $action" >&2
    exit 1
esac

exit 0

